[workspace]
members = ["app_core"]
# members = ["app_core", "shell_cli"]

[workspace.package]
authors = ["PSTT"]
edition = "2021"
repository = "https://github.com/patmuk/sherry"
license = "Apache-2.0"
keywords = ["photos", "sharring"]

[workspace.dependencies]
thiserror = "^1.0.40"
