
[workspace]
# members = ["app_core", "cqrs_core", "cqrs_macros", "shell_cli"]
members = ["app_core", "shell_cli"]

[workspace.package]
resolver = "2"
authors = ["PSTT"]
edition = "2021"
repository = "https://github.com/patmuk/sherry"
license = "Apache-2.0"
keywords = ["photos", "sharring"]

[workspace.dependencies]
thiserror = "^1.0.40"
tokio = { version = "^1.40.0", features = ["rt", "macros"] }
