// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import '../../lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they have generic arguments: `init`, `init`, `load_or_new`, `load_or_new`

abstract class AppConfig {
  Future<void> getAppStateFilePath();
}

abstract class AppState {
  Future<bool> dirtyFlagValue();

  Future<void> markDirty();

  Future<void> persistToPath({required PathBuf path});
}

abstract class Lifecycle {
  Future<void> appConfig();

  Future<void> appState();

  Future<void> persist();

  Future<void> shutdown();
}
