// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.5.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../domain/effects.dart';
import '../../domain/todo_list.dart';
import '../../frb_generated.dart';
import '../processing_errors.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'processing.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `process_with_app_state`

@freezed
sealed class Cqrs with _$Cqrs {
  const Cqrs._();

  const factory Cqrs.todoCommandAddTodo(
    String field0,
  ) = Cqrs_TodoCommandAddTodo;
  const factory Cqrs.todoCommandRemoveTodo(
    BigInt field0,
  ) = Cqrs_TodoCommandRemoveTodo;
  const factory Cqrs.todoCommandCleanList() = Cqrs_TodoCommandCleanList;
  const factory Cqrs.todoQueryAllTodos() = Cqrs_TodoQueryAllTodos;

  Future<List<Effect>> process() =>
      RustLib.instance.api.crateApplicationApiProcessingCqrsProcess(
        that: this,
      );
}
