rust_input: [src/lib_crux.rs]
dart_output: [../shell_flutter/lib/bridge_generated.dart]
wasm: true
dart_decl_output: ../shell_flutter/lib/bridge_definitions.dart
dart_format_line_length: 120
dart_enums_style: true
c_output: [../shell_flutter/ios/Runner/bridge_generated.h]
#extra_c_output_path:
#  - c_output_path_extra/
# dump: []