[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
log = "0.4"

flutter_rust_bridge = "1"

# handles the app state with a mutex
parking_lot = { version = "0.12", features = ["serde"] }

[build-dependencies]
flutter_rust_bridge_codegen = { workspace = true}
