[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.5.0"
thiserror = "^1.0.51"

log = "^0.4"
serde = { version = "^1.0.154", features = ["derive"] }
bincode = "^1.3.3"

quote = "1.0.37"
syn = "2.0.79"
cps = "0.2.3"
proc-macro2 = "1.0.88"

[dev-dependencies]
serial_test = "3.0.0"

[build-dependencies]
flutter_rust_bridge_codegen = "=2.4.0"
anyhow = "1.0"
