[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
log = "0.4"

flutter_rust_bridge = { version = "1", features = ["zero-copy"] }
serde = "^1.0.154"
bincode = "^1.3.3"
# handles the app state with a mutex
once_cell = "^1.19.0"
parking_lot = { version = "0.12", features = ["serde"] }
anyhow = "^1.0.75"
oslog = "^0.2.0"

[build-dependencies]
flutter_rust_bridge_codegen = { workspace = true}
