[package]
name = "app_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["lib", "staticlib", "cdylib"]

[dependencies]
flutter_rust_bridge = "^2.0.0-dev.2"

thiserror = "^1.0.51"

log = "^0.4"
oslog = "^0.2.0"

serde = "^1.0.154"
bincode = "^1.3.3"

# handles the app state with a mutex
once_cell = "^1.19.0"
parking_lot = { version = "0.12", features = ["serde"] }


[build-dependencies]
flutter_rust_bridge_codegen = "^2.0.0-dev.2"
