// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class AppConfigImpl {
  /// app state storage location
  final String appStateUrl;

  const AppConfigImpl({
    required this.appStateUrl,
  });

  Future<void> borrowAppStateUrl() => RustLib.instance.api
          .crateApplicationAppConfigAppConfigImplBorrowAppStateUrl(
        that: this,
      );

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  /// call to overwrite default values.
  /// Doesn't trigger long initialization operations.
  static Future<AppConfigImpl> newInstance({String? url}) =>
      RustLib.instance.api.crateApplicationAppConfigAppConfigImplNew(url: url);

  @override
  int get hashCode => appStateUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfigImpl &&
          runtimeType == other.runtimeType &&
          appStateUrl == other.appStateUrl;
}
